### ISSUE TITLE
How to deal with discrete data?

### ISSUE THREAD

**Issue by torivv** [TheHedgeify/DagstuhlGAN#2]
Tiles are represented by integers between 0 and 9. How do you back-propagate from the GAN discriminator to the generator? I wonder.

**Comment by schrum2** [comment]
The output is one-hot encoded, so that for each position one of the tiles has a 1.0 and the rest have 0.0.

To produce levels from the generator, we use arg-max at each position to pick the one tile that is present.

**Comment by torivv** [comment]
As far as I can tell, a common gan can not handle discrete data such as text.
Note: https://www.reddit.com/r/MachineLearning/comments/40ldq6/generative_adversarial_networks_for_text/
However, in this paper, tiles are discrete data between 0 and 9, and they are expressed in one-hot encoding.
I think that when you propagate the loss from the discriminator to the generator, there seems to be a problem like the above text. What do you think?

**Comment by marshsh** [comment]
Hello,
I would really like to use your article for a class project, but I couldn't "build" it or run it.
Do you have further instructions ?
The project seems to be missing the "DagstuhlGAN/marioaiDagstuhl/lib/nblibraries.properties"
Thank you very much!

**Comment by TheHedgeify** [comment]
@schrum2 pointed out to me that this is likely a NetBeans issue.

Are you using NetBeans? If you are, I would try to remove all NetBeans files that are in the git (they should not be there to begin with, I think). Then you'd need to create a new project with existing sources in NetBeans. Don't forget to add the libraries to the project: https://github.com/TheHedgeify/DagstuhlGAN/tree/master/marioaiDagstuhl/lib
Examples of these NetBeans files are: https://github.com/TheHedgeify/DagstuhlGAN/tree/master/marioaiDagstuhl/nbproject

If you aren't, what IDE are you using? Are you able to compile via command line?

**Comment by marshsh** [comment]
WoW!    Thank you so very much for answering!

I was using NetBeans and finally got to build it, but then tried with Eclipse and everything went much smoother. Which IDE where you using?

I've set the Settings.PYTHON_PROGRAM = "/home/mariana/anaconda3/bin/python3.6";
to my Python program PATH, created a my/_python/_path.txt directly under DagstuhlGAN-master folder, containing:
/home/mariana/anaconda3/bin/python3.6


And now I just have an issue with PyTorch. Apparently, now, when using " add_module " in a torch.nn.Sequential object, we can't use "." in the module name.

Thank you very very much!
:D

**Comment by TheHedgeify** [comment]
Glad to hear that you solved this issue. The issue you describe sounds a lot lke a pytorch versioning issue we had before. If I remember correctly, @schrum2  resolved this before? Which version of the code are you using and which branch?

**Comment by marshsh** [comment]
I loaded the project using Eclipse:

Eclipse -> File -> Import... -> Git -> Projects from Git -> Clone from Url : https://github.com/TheHedgeify/DagstuhlGAN

And selected all branches.

**Comment by marshsh** [comment]
This is the Console message:

Process buffers initialized
[INFO] GANThread has started
competition.icegic.robin.AStarAgent
Traceback (most recent call last):
  File "pytorch/generator_ws.py", line 55, in <module>
    generator = dcgan.DCGAN_G(imageSize, nz, z_dims, ngf, ngpu, n_extra_layers)
  File "/home/mariana/git/DagstuhlGAN/pytorch/models/dcgan.py", line 69, in __init__
    nn.ConvTranspose2d(nz, cngf, 4, 1, 0, bias=False))
  File "/home/mariana/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 178, in add_module
    raise KeyError("module name can't contain \".\"")
KeyError: 'module name can\'t contain "."'
processCommRecv:null
Exception in thread "main" [ERROR] processCommRecv: Null message.
java.lang.NullPointerException
	at cmatest.MarioEvalFunction.<init>(MarioEvalFunction.java:40)
	at viewer.MarioRandomLevelViewer.main(MarioRandomLevelViewer.java:86)



This is the code from file  DagstuhlGAN/pytorch/models/dcgan.py", arround line 69, and it looks the same in GitHub

        main = nn.Sequential()
        # input is Z, going into a convolution
        main.add_module('initial.{0}-{1}.convt'.format(nz, cngf),
                        nn.ConvTranspose2d(nz, cngf, 4, 1, 0, bias=False))
        main.add_module('initial.{0}.batchnorm'.format(cngf),
                        nn.BatchNorm2d(cngf))
        main.add_module('initial.{0}.relu'.format(cngf),
                        nn.ReLU(True))

**Comment by schrum2** [comment]
This is indeed a PyTorch version issue. PyTorch upgraded the name allowances in a way that broke this code. The easiest way to get our code running is to simply use an older version of PyTorch ( @TheHedgeify can let you know which version ). However, this is probably not satisfying in the long run. 

I have actually fixed this issue, but in different places. I don't currently have access to a computer than can run this code, so I can only give you advice based on memory.

First, there is a branch called new_pytorch_compatibility that partially addresses this issue. I had even created a pull request for this ( https://github.com/TheHedgeify/DagstuhlGAN/pull/3 ), but we decided not to merge it because although it is possible to load our pre-existing models with this code, you might have trouble training and loading new models. Of course, if you just want to look at our previous results, then perhaps this is enough.

I then went off and did a lot of work with this code in different repositories to the point where I can't remember what the specific changes were. However, I believe that the most up-to-date version of this code is in this location: https://github.com/schrum2/GameGAN/tree/master/python/GAN . You will also need the files in https://github.com/schrum2/GameGAN/tree/master/python/GAN/models . I know that this version of the code fixes the PyTorch compatibility issue, but I think it also changes the command line parameters in a way that might make it incompatible with the DagstuhlGAN repo.

I won't be able to address this issue myself for a while, but I figured I would give you some guidance now in case you can fix the issue yourself using what I've pointed out.

**Comment by marshsh** [comment]
Thank you very much !

I'll stick to the older pytorch version.
